-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    general = {
        allow_tearing = false,
        border_size = 2,
        col = {
            active_border = {
                colors = {"rgba(9a9996ff)", "rgba(595959aa)"},
                angle = 45,
            },
            inactive_border = "0xff1a5fb4",
        },
        resize_on_border = false,
    },
    input = {
        numlock_by_default = true,
    },
    misc = {
        mouse_move_enables_dpms = false,
    },
})
